apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contoso-motors
  namespace: default
spec:
  interval: 1m
  releaseName: contoso-motors
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./contoso_manufacturing/charts/opc-simulator
      version: '0.1.0'