apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mike-fork-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/mrhoads/jumpstart-agora-apps
  ref:
    branch: mfg-flux-troubleshooting