apiVersion: v1
kind: ConfigMap
metadata:
    name: rtsp-helmet-config
data:
    SOURCE_URL: "file:///samples/helmet.mp4"
    DOWNLOAD_URL: "https://jsfiles.blob.core.windows.net/video/agora/helmet-detection.mp4"

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: rtsp-welding-config
data:
    SOURCE_URL: "file:///samples/welding.mp4"
    DOWNLOAD_URL: "https://jsfiles.blob.core.windows.net/video/agora/welding.mp4"

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: rtsp-pose-config
data:
    SOURCE_URL: "file:///samples/pose.mp4"
    DOWNLOAD_URL: "https://jsfiles.blob.core.windows.net/video/agora/pose-estimation.mp4"

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: rtsp-object-config
data:
    SOURCE_URL: "file:///samples/object-detection.mp4"
    DOWNLOAD_URL: "https://jsfiles.blob.core.windows.net/video/agora/object-detection.mp4"